# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

points = Point.create([{ :name => "Golding Judaic Center",
                         :lat => 42.37009,
                         :lng => -71.25777},
                       { :name => "Lown School of Near Eastern and Judaic Studies",
                         :lat => 42.37015,
                         :lng => -71.2572},
                       { :name => "Gordon Residence Hall",
                         :lat => 42.369603,
                         :lng => -71.256863},
                       { :name => "Reitman Residence Hall",
                         :lat => 42.369603,
                         :lng => -71.256863},
                       { :name => "Cable Residence Hall",
                         :lat => 42.369603,
                         :lng => -71.256863},
                       { :name => "Kutz Hall",
                         :lat => 42.369603,
                         :lng => -71.256863},
                       { :name => "Schefferes Residence Hall",
                         :lat => 42.369603,
                         :lng => -71.256863},
                       { :name => "Rabb Graduate Center",
                         :lat => 42.369603,
                         :lng => -71.256863},
                       { :name => "Shiffman Humanities Center",
                         :lat => 42.369832,
                         :lng => -71.257104},
                       { :name => "Olin-Sang American Civilization Center",
                         :lat => 42.369832,
                         :lng => -71.25747},
                       { :name => "Goldfarb Library",
                         :lat => 42.368762,
                         :lng => -71.257517},
                       { :name => "Usdan Student Center",
                         :lat => 42.368762,
                         :lng => -71.257517},
                       { :name => "Schwartz Hall",
                         :lat => 42.368762,
                         :lng => -71.257517},
                       { :name => "Lemberg Hall",
                         :lat => 42.368762,
                         :lng => -71.257313},
                       { :name => "Usen Castle",
                         :lat => 42.368548,
                         :lng => -71.257313}])
